In [23]:
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.ticker import MaxNLocator
from scipy import ndimage
from scipy.io import loadmat
import pandas as pd
import os
%matplotlib inline

In [24]:
import import_ipynb
try:
    os.chdir('C:\\Users\\hydro_leo\\Documents\\GitHub\\python-code\\Modules')
except:
    os.chdir('C:\\Users\\llinc\\GitHub\\python-code\\Modules')
from time_shifted_PID import Histo3D2Dict
from time_shifted_PID import PIfunc
from time_shifted_PID import EqualState
from Spike_Generation import Spike_Time_Generater
from Spike_Generation import NL
from StimulusnResponse import expSnR
from SpatialTemporal_Correlation_and_Convolution import ST_STA
from NGD_TK_AS import NGD2L_TK_AS
from NGD_TK_AS import ParaTrans

In [25]:
x = np.random.randint(2, size = 30000)
y = np.random.randint(2, size = 30000)

xy = np.vstack((x,y))
_, xy = np.unique(xy, return_inverse=True,  axis=1)

In [26]:
_, px = np.unique(x, return_counts=True)
px/sum(px)

array([0.5005, 0.4995])

In [27]:
_, py = np.unique(y, return_counts=True)
py/sum(py)

array([0.50076667, 0.49923333])

In [28]:
_, pxy = np.unique(xy, return_counts=True)
pxy/sum(pxy)

array([0.24763333, 0.25286667, 0.25313333, 0.24636667])

In [29]:
((px/sum(px))[:,np.newaxis] * (py/sum(py))[np.newaxis,:])

array([[0.25063372, 0.24986628],
       [0.25013295, 0.24936705]])